CLASS zcl_square_abs DEFINITION
  PUBLIC
  ABSTRACT
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS:
      get_perimeter ABSTRACT RETURNING VALUE(rv_per) TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_SQUARE_ABS IMPLEMENTATION.
ENDCLASS.
